const PARAM_START_SYMBOL = '?';

const PARAM_AND_SEPARATOR = '&';

const EXCEL_FILE_NAME_SEPARATOR = '_';

const HISTORY_SEPARATOR = '-';

const  EXCEL_FILE_EXTENSION = '.xlsx';

const LIMIT_DEFAULT = 20;

export { 
  PARAM_AND_SEPARATOR, 
  PARAM_START_SYMBOL, 
  LIMIT_DEFAULT, 
  EXCEL_FILE_NAME_SEPARATOR,
  EXCEL_FILE_EXTENSION,
  HISTORY_SEPARATOR
};